- name: set authorized key
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags: init

- name: group
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
  with_items:
    - { name: 'admin', gid: 1777 }
    - { name: 'fakeadm', gid: 1888 }
  tags: init

- name: create user
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    shell: "{{ item.shell }}"
  with_items:
    - { name: 'admin', uid: '1777', group: 'admin', shell: '/bin/bash' }
    - { name: 'fakeadm', uid: '1888', group: 'fakeadm', shell: '/bin/bash' }
  tags: init

- name: set authorized key
  authorized_key:
    user: "{{ item.user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" 
  with_items:
    - { user: 'admin' }
    - { user: 'fakeadm' }
  tags: init
 
- name: install sudo 
  apt:
    name: sudo
    update_cache: yes
  tags: init

- name: copy suders file
  copy:
    src: sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: '0400'
    backup: yes
  tags: init

- name: copy sshd config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify:
    - restart sshd
  tags: init


- name: config bbr
  copy: 
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: '0644'
  tags: init

- name: reload sysctl
  command: sysctl -p
  tags: init
